spring.application.name=Server
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/creditcards_db
spring.datasource.username=postgres
spring.datasource.password=slr300hdg6m1239
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# Server Configuration
server.port=8081
# Enable cache debugging (optional)
logging.level.org.springframework.cache=TRACE
# Cache statistics (optional)
spring.cache.caffeine.spec=recordStats
